name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      - name: Install .NET WebAssembly Tools
        run: dotnet workload install wasm-tools

      # Publish the site
      - name: Publish
        run: dotnet publish src/GameboyColorReducer.Wasm/GameboyColorReducer.Wasm.csproj -c:Release -o:publish -p:GHPages=true

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: publish/wwwroot/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment